apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://prometheus:9090'
    password:
    user:
    database:
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: 'POST'
    version: 1
    editable: true
